apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-manager-backend
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70 # Scale up if CPU goes over 70%